#!/usr/bin/env bash
set -euo pipefail

# ─── GCE Startup Script ───
# Runs on first boot and every reboot of the Compute Engine instance.
# Installs Docker, clones repo, pulls secrets, starts services.

LOG="/var/log/scopio-startup.log"
exec > >(tee -a "$LOG") 2>&1
echo "$(date) — Scopio startup script begin"

PROJECT="scopio-lab-bpa-demo"
REPO_URL="https://github.com/gilshneorson-tech/scopio_lab_BPA_demo.git"
DEPLOY_DIR="/opt/scopio"

# ─── 1. Install Docker ───
if ! command -v docker &>/dev/null; then
  echo "Installing Docker..."
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable docker
  systemctl start docker
  echo "Docker installed"
else
  echo "Docker already installed"
fi

# ─── 2. Install gcloud (if not present) ───
if ! command -v gcloud &>/dev/null; then
  echo "Installing gcloud CLI..."
  apt-get install -y apt-transport-https
  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" > /etc/apt/sources.list.d/google-cloud-sdk.list
  curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
  apt-get update -y
  apt-get install -y google-cloud-cli
  echo "gcloud installed"
fi

# ─── 3. Clone or update repo ───
if [ -d "$DEPLOY_DIR/.git" ]; then
  echo "Updating repo..."
  cd "$DEPLOY_DIR"
  git pull origin main
else
  echo "Cloning repo..."
  git clone "$REPO_URL" "$DEPLOY_DIR"
  cd "$DEPLOY_DIR"
fi

# ─── 3.5. Download Zoom SDK from GCS (if not already present) ───
SDK_DIR="$DEPLOY_DIR/services/zoom-bot/sdk/zoomsdk"
if [ ! -f "$SDK_DIR/libmeetingsdk.so" ]; then
  echo "Downloading Zoom SDK from GCS..."
  mkdir -p "$SDK_DIR"
  gsutil cp gs://scopio-lab-bpa-demo-sdk/zoom-meeting-sdk-linux_x86_64-7.0.0.tar.gz /tmp/zoomsdk.tar.gz
  tar xzf /tmp/zoomsdk.tar.gz -C "$DEPLOY_DIR/services/zoom-bot/sdk/"
  rm /tmp/zoomsdk.tar.gz
  echo "Zoom SDK extracted to $SDK_DIR"
else
  echo "Zoom SDK already present"
fi

# ─── 4. Pull secrets from Secret Manager → .env ───
echo "Pulling secrets from Secret Manager..."

get_secret() {
  gcloud secrets versions access latest --secret="$1" --project="$PROJECT" 2>/dev/null || echo ""
}

cat > "$DEPLOY_DIR/.env" <<ENVEOF
# Auto-generated by gce-startup.sh — do not edit manually
ANTHROPIC_API_KEY=$(get_secret ANTHROPIC_API_KEY)
ELEVENLABS_API_KEY=$(get_secret ELEVENLABS_API_KEY)
ZOOM_ACCOUNT_ID=$(get_secret ZOOM_ACCOUNT_ID)
ZOOM_CLIENT_ID=$(get_secret ZOOM_CLIENT_ID)
ZOOM_CLIENT_SECRET=$(get_secret ZOOM_CLIENT_SECRET)
ZOOM_MEETING_ID=
ZOOM_MEETING_PASSWORD=
ELEVENLABS_VOICE_ID=21m00Tcm4TlvDq8ikWAM
TTS_MODEL=eleven_turbo_v2
GOOGLE_CLOUD_PROJECT=$PROJECT
STT_LANGUAGE=en-US
BMA_URL=
BMA_USERNAME=
BMA_PASSWORD=
AGENT_NAME=Alex
LOG_LEVEL=info
AUDIO_INPUT_FILE=
AUDIO_OUTPUT=file
ENVEOF

chmod 600 "$DEPLOY_DIR/.env"
echo "Secrets written to .env"

# ─── 5. Build and start services ───
echo "Starting Docker Compose..."
cd "$DEPLOY_DIR"
docker compose pull 2>/dev/null || true
docker compose up --build -d

echo "$(date) — Scopio startup script complete"
echo "Dashboard: http://$(curl -sf http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip -H 'Metadata-Flavor: Google'):3000"
