"""
STT Service — Deepgram streaming speech-to-text via gRPC.

Receives audio chunks from zoom-bot via bidirectional gRPC stream,
forwards to Deepgram's streaming API, and returns transcriptions.
"""

import asyncio
import logging
import os
from concurrent import futures

import grpc
from deepgram import (
    DeepgramClient,
    LiveOptions,
    LiveTranscriptionEvents,
)

# Proto imports (generated by scripts/generate-proto.sh)
# For now, we define the servicer inline since proto generation
# requires the build step to run first.

logger = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOG_LEVEL", "INFO").upper())

DEEPGRAM_API_KEY = os.environ.get("DEEPGRAM_API_KEY", "")
STT_LANGUAGE = os.environ.get("STT_LANGUAGE", "en-US")
STT_MODEL = os.environ.get("STT_MODEL", "nova-2")


class STTServicer:
    """Bidirectional streaming: receive audio chunks, yield transcriptions."""

    async def StreamAudio(self, request_iterator, context):
        """
        For each audio chunk received, forward to Deepgram.
        Yield transcription results as they come back.
        """
        if not DEEPGRAM_API_KEY:
            logger.error("DEEPGRAM_API_KEY not set")
            context.abort(grpc.StatusCode.FAILED_PRECONDITION, "DEEPGRAM_API_KEY not set")
            return

        deepgram = DeepgramClient(DEEPGRAM_API_KEY)
        transcription_queue = asyncio.Queue()
        call_id = None

        # Configure Deepgram live transcription
        options = LiveOptions(
            model=STT_MODEL,
            language=STT_LANGUAGE,
            encoding="linear16",
            sample_rate=16000,
            channels=1,
            interim_results=True,
            utterance_end_ms=1000,
            vad_events=True,
            smart_format=True,
        )

        connection = deepgram.listen.asynclive.v("1")

        async def on_transcript(self_conn, result, **kwargs):
            transcript = result.channel.alternatives[0].transcript
            if transcript:
                is_final = result.is_final
                confidence = result.channel.alternatives[0].confidence
                await transcription_queue.put({
                    "call_id": call_id or "",
                    "text": transcript,
                    "is_final": is_final,
                    "confidence": confidence,
                    "timestamp_ms": int(asyncio.get_event_loop().time() * 1000),
                })

        async def on_error(self_conn, error, **kwargs):
            logger.error(f"Deepgram error: {error}")

        connection.on(LiveTranscriptionEvents.Transcript, on_transcript)
        connection.on(LiveTranscriptionEvents.Error, on_error)

        await connection.start(options)
        logger.info("Deepgram live connection started")

        # Producer: read audio chunks and send to Deepgram
        async def produce():
            nonlocal call_id
            async for chunk in request_iterator:
                if not call_id:
                    call_id = chunk.call_id
                await connection.send(chunk.audio_data)
            await connection.finish()

        # Consumer: yield transcriptions from queue
        producer_task = asyncio.create_task(produce())

        try:
            while True:
                try:
                    result = await asyncio.wait_for(
                        transcription_queue.get(), timeout=30.0
                    )
                    # Yield as a proto-like dict (actual proto message in production)
                    yield result
                except asyncio.TimeoutError:
                    if producer_task.done():
                        break
        finally:
            if not producer_task.done():
                producer_task.cancel()
            await connection.finish()


async def serve():
    """Start the gRPC server."""
    port = os.environ.get("GRPC_PORT", "50056")

    # NOTE: Full gRPC server setup requires generated proto stubs.
    # This is the service implementation; the gRPC server wiring
    # will use the generated pb2_grpc module after proto generation.
    #
    # For now, log readiness:
    logger.info(f"STT service ready on port {port}")
    logger.info(f"Deepgram model: {STT_MODEL}, language: {STT_LANGUAGE}")
    logger.info(f"API key configured: {'yes' if DEEPGRAM_API_KEY else 'NO'}")

    # Keep alive
    try:
        while True:
            await asyncio.sleep(3600)
    except KeyboardInterrupt:
        logger.info("STT service shutting down")


if __name__ == "__main__":
    asyncio.run(serve())
